#!/bin/bash

# Create an X Virtual Frame Buffer (wait for it to start)
Xvfb :2 -screen 0 1041x768x24 -fbdir /tmp -nolisten inet6 &>/dev/null &
XVFB_PID=$!

# Make sure it has started and is sorted
sleep 120

# Make sure we're in the right folder
cd /var/www/screenshots.scratchpads.eu

# While Xvfb is running (in case of crash)
while kill -0 $XVFB_PID
do
	# For each site.
	for i in $(ls -1 /var/lib/drupal* | sort | uniq | grep -v "/" | grep -v "^d6." | sed "/^$/d" | grep "\.")
	do
		./firefox-screenshot $i
	done
done

# Finally, kill the XVFB
kill -9 $XVFB_PID &>/dev/null

