#!/bin/bash

# Create an X Virtual Frame Buffer (wait for it to start)
Xvfb :2 -screen 0 1040x768x24 -fbdir /tmp -nolisten inet6 &>/dev/null &

# Make sure it has started and is sorted
sleep 60

# Make sure we're in the right folder
cd /var/www/screenshots.scratchpads.eu

# For each site.
for i in $(ls -1 /var/lib/drupal* | sort | uniq | grep -v "/" | grep -v "^d6." | sed "/^$/d" | grep "\.")
do
	./firefox-screenshot $i
done

# Finally, kill the XVFB
killall -9 Xvfb
