#!/bin/bash

# Create an X Virtual Frame Buffer (wait for it to start)
Xvfb :2 -screen 0 1041x768x24 -fbdir /tmp -nolisten inet6 &>/dev/null &
XVFB_PID=$!

# Make sure it has started and is sorted
sleep 15

# Make sure we're in the right folder
cd /var/www/screenshots.scratchpads.eu

# Create the file
./take-screenshot-and-resize $1 1200 900

# Finally, kill the XVFB
kill -9 $XVFB_PID &>/dev/null

