#!/bin/bash
DISPLAY=:2.0 firefox -width 1038 -height 2000 http://$1 &
sleep 15
DISPLAY=:2.0 import -window root $1.long.jpg
convert $1.long.jpg -crop 1024x2000+1+1 $1.long.jpg
killall -9 firefox firefox-bin &>/dev/null