#!/bin/bash
echo $1
DISPLAY=:2.0 firefox http://$1 &>/dev/null &
FIREFOX_PID=$!
sleep 15
FILENAME=`echo $1|sed "s|/||g"`
DISPLAY=:2.0 import -window root $FILENAME".jpg"
convert $FILENAME".jpg" -crop 1024x768+1+1 $FILENAME".jpg"
convert $FILENAME".jpg" -resize 300x225 $FILENAME".small.jpg"
kill -9 $FIREFOX_PID &>/dev/null

